'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'id' | 'en' | 'ja' | 'ko' | 'zh';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  id: {
    newChat: 'Chat Baru',
    chatHistory: 'Riwayat Chat',
    settings: 'Pengaturan',
    help: 'Bantuan',
    askAnything: 'Tanyakan apa saja',
    askLearning: 'Topik apa yang ingin Anda pelajari hari ini?',
    noHistory: 'Belum ada riwayat',
    noResult: 'Tidak ada hasil',
    searchHistory: 'Cari riwayat...',
    logoutConfirmTitle: 'Keluar dari Zhiyou?',
    logoutConfirmDesc: 'Anda harus login kembali untuk mengakses riwayat chat Anda.',
    cancel: 'Batal',
    yesLogout: 'Ya, Keluar',
    deleteChatTitle: 'Hapus riwayat chat?',
    deleteChatDesc: 'Chat ini akan dihapus secara permanen dan tidak dapat dikembalikan.',
    delete: 'Hapus',
    login: 'Login',
    welcome: 'Halo',
    howCanIHelp: "Saya Zhiyou AI. Ada yang bisa saya bantu hari ini?",
    addImage: 'Gambar',
    addVideo: 'Video',
    addDoc: 'Dokumen',
    addFile: 'Tambahkan file',
    fileTooLarge: 'Ukuran file terlalu besar. Maksimal 20MB.',
    fileTypeNotSupported: 'Tipe file tidak didukung.',
    fileReadError: 'Gagal membaca file.',
    uploading: 'Mengunggah...',
    done: 'Selesai',
    magicTool: 'Gunakan alat ajaib',
    searchWeb: 'Cari di Web',
    sources: 'Sumber',
    others: 'lainnya',
    copySuccess: 'Teks disalin!',
    shareSuccess: 'Berhasil dibagikan!',
    feedbackTitle: 'Kirim Masukan',
    feedbackPlaceholder: 'Beritahu kami apa yang salah...',
    submit: 'Kirim',
    disclaimer: 'Zhiyou AI dapat membuat kesalahan. Harap periksa kembali info penting.',
    language: 'Bahasa',
    selectLanguage: 'Pilih Bahasa',
    backToHome: 'Kembali ke Beranda',
    save: 'Simpan',
    thinking: 'berpikir',
    searching: 'mencari',
    modelZhiyou25: 'Zhiyou 2.5',
    modelZhiyou25Desc: 'Cepat & efisien',
    modelZhiyou3: 'Zhiyou 3',
    modelZhiyou3Desc: 'Penalaran & matematika',
    aspectRatio: 'Aspek Rasio',
    systemPromptBase: "Anda adalah Zhiyou AI, asisten AI yang cerdas dan ramah dari Zent Technology GH. Jangan terlalu sering menyebutkan nama pendiri atau pengembang kecuali ditanya secara eksplisit. Fokuslah pada identitas Anda sebagai Zhiyou AI.",
    systemPromptLang: "Harap selalu merespons dalam bahasa Indonesia.",
    systemPromptReasoning: "Anda sekarang beroperasi sebagai Zhiyou 3. Awali jawaban Anda dengan kalimat 'Sebagai Zhiyou AI, saya akan menganalisis...' cukup satu kali saja di awal. Anda harus berpikir sangat mendalam, selangkah demi selangkah (step-by-step), menganalisis setiap sudut pandang sebelum memberikan jawaban. Anda WAJIB meletakkan seluruh proses pemikiran/penalaran Anda di dalam tag <think> dan </think>. Setelah tag </think>, berikan jawaban akhir Anda yang sangat komprehensif, logis, dan terstruktur. Jangan terburu-buru memberikan kesimpulan.",
    reasoningProcess: "Proses Penalaran",
    systemPromptResearch: "Anda sekarang bertindak sebagai Peneliti Senior (Senior Researcher). Awali jawaban Anda dengan kalimat 'Sebagai Zhiyou AI, saya akan meriset data tentang...' cukup satu kali saja di awal. Tugas Anda adalah melakukan riset mendalam terhadap topik yang diberikan. Gunakan alat pencarian Google untuk menemukan informasi terbaru, akurat, dan dari berbagai sumber. Berikan laporan riset yang sangat komprehensif, mencakup latar belakang, analisis mendalam, data pendukung, dan kesimpulan yang kuat. Gunakan format Markdown yang sangat terstruktur dengan tabel, daftar, dan kutipan jika diperlukan.",
    systemPromptLearning: "Anda sekarang bertindak sebagai Tutor Pribadi (Personal Tutor) dalam mode Pembelajaran Terpandu. Awali jawaban Anda dengan kalimat 'Sebagai Zhiyou AI, mari kita pelajari ini bersama-sama...' cukup satu kali saja di awal. Tugas Anda adalah memberikan penjelasan langkah demi langkah (step-by-step) tentang topik yang ditanyakan. Gunakan alat pencarian Google untuk menyertakan sumber yang relevan dan akurat. Pecah konsep yang kompleks menjadi bagian-bagian yang mudah dipahami, gunakan analogi jika perlu, dan berikan contoh konkret. Selalu sertakan tautan sumber di akhir penjelasan.",
    featureGenerateImage: 'Buat Gambar',
    imageGenSuccess: 'Sebagai Zhiyou AI, saya telah membuat gambar berdasarkan permintaan Anda:',
    imageSearchSuccess: 'Sebagai Zhiyou AI, saya telah menemukan beberapa gambar yang relevan untuk Anda:',
    featureDeepResearch: 'Riset (Deep Research)',
    featureGuidedLearning: 'Pembelajaran Terpandu',
    featureSearchImage: 'Cari Gambar',
    describeSearchImage: 'Deskripsikan gambar yang ingin dicari',
    featureComingSoon: 'Fitur ini akan segera hadir!',
    signIn: 'Masuk',
    newUser: 'Pengguna baru?',
    createAccount: 'Buat akun',
    emailAddress: 'Alamat Email',
    password: 'Kata Sandi',
    forgotPassword: 'Lupa kata sandi?',
    continueWithGoogle: 'Lanjutkan dengan Google',
    loginError: 'Gagal login dengan Google. Silakan coba lagi.',
    emailLoginNotImplemented: 'Login dengan email belum diimplementasikan.',
    termsAndPrivacy: 'Dengan masuk menggunakan akun, Anda menyetujui Ketentuan Layanan dan Kebijakan Privasi SO.',
  },
  en: {
    newChat: 'New Chat',
    chatHistory: 'Chat History',
    settings: 'Settings',
    help: 'Help',
    askAnything: 'Ask anything',
    askLearning: 'What topic do you want to learn today?',
    noHistory: 'No history yet',
    noResult: 'No results',
    searchHistory: 'Search history...',
    logoutConfirmTitle: 'Sign out of Zhiyou?',
    logoutConfirmDesc: 'You will need to sign in again to access your chat history.',
    cancel: 'Cancel',
    yesLogout: 'Yes, Sign Out',
    deleteChatTitle: 'Delete chat history?',
    deleteChatDesc: 'This chat will be permanently deleted and cannot be recovered.',
    delete: 'Delete',
    login: 'Log in',
    welcome: 'Hello',
    howCanIHelp: "I'm Zhiyou AI. How can I help you today?",
    addImage: 'Image',
    addVideo: 'Video',
    addDoc: 'Document',
    addFile: 'Add file',
    fileTooLarge: 'File size is too large. Maximum is 20MB.',
    fileTypeNotSupported: 'File type is not supported.',
    fileReadError: 'Failed to read file.',
    uploading: 'Uploading...',
    done: 'Done',
    magicTool: 'Use magic tool',
    searchWeb: 'Search Web',
    sources: 'Sources',
    others: 'others',
    copySuccess: 'Text copied!',
    shareSuccess: 'Shared successfully!',
    feedbackTitle: 'Send Feedback',
    feedbackPlaceholder: 'Tell us what went wrong...',
    submit: 'Submit',
    disclaimer: 'Zhiyou AI can make mistakes. Please verify important info.',
    language: 'Language',
    selectLanguage: 'Select Language',
    backToHome: 'Back to Home',
    save: 'Save',
    thinking: 'thinking',
    searching: 'searching',
    modelZhiyou25: 'Zhiyou 2.5',
    modelZhiyou25Desc: 'Fast & efficient',
    modelZhiyou3: 'Zhiyou 3',
    modelZhiyou3Desc: 'Reasoning & math',
    aspectRatio: 'Aspect Ratio',
    systemPromptBase: "You are Zhiyou AI, a smart and friendly AI assistant from Zent Technology GH. Do not mention the founder or developer too often unless explicitly asked. Focus on your identity as Zhiyou AI.",
    systemPromptLang: "Please always respond in English.",
    systemPromptReasoning: "You are now operating as Zhiyou 3. Start your response with 'As Zhiyou AI, I will analyze...' only once at the beginning. You must think very deeply, step-by-step, analyzing every perspective before providing an answer. You MUST put your entire thinking/reasoning process inside <think> and </think> tags. After the </think> tag, provide your final answer which should be very comprehensive, logical, and structured. Do not rush to conclusions.",
    reasoningProcess: "Reasoning Process",
    systemPromptResearch: "You are now acting as a Senior Researcher. Start your response with 'As Zhiyou AI, I will research data about...' only once at the beginning. Your task is to conduct in-depth research on the given topic. Use Google search tools to find the latest, accurate information from various sources. Provide a very comprehensive research report, covering background, in-depth analysis, supporting data, and strong conclusions. Use highly structured Markdown format with tables, lists, and citations where necessary.",
    systemPromptLearning: "You are now acting as a Personal Tutor in Guided Learning mode. Start your response with 'As Zhiyou AI, let's learn this together...' only once at the beginning. Your task is to provide a step-by-step explanation of the requested topic. Use Google search tools to include relevant and accurate sources. Break down complex concepts into easy-to-understand parts, use analogies if necessary, and provide concrete examples. Always include source links at the end of your explanation.",
    featureGenerateImage: 'Generate Image',
    imageGenSuccess: 'As Zhiyou AI, I have created the image based on your request:',
    imageSearchSuccess: 'As Zhiyou AI, I have found several relevant images for you:',
    featureDeepResearch: 'Deep Research',
    featureGuidedLearning: 'Guided Learning',
    featureSearchImage: 'Search Images',
    describeSearchImage: 'Describe the image you want to find',
    featureComingSoon: 'This feature is coming soon!',
    signIn: 'Sign in',
    newUser: 'New user?',
    createAccount: 'Create an account',
    emailAddress: 'Email Address',
    password: 'Password',
    forgotPassword: 'Forgot password?',
    continueWithGoogle: 'Continue with Google',
    loginError: 'Failed to sign in with Google. Please try again.',
    emailLoginNotImplemented: 'Email login is not implemented yet.',
    termsAndPrivacy: 'By signing in with an account, you agree to SO\'s Terms of Service and Privacy Policy.',
  },
  ja: {
    newChat: '新しいチャット',
    chatHistory: 'チャット履歴',
    settings: '設定',
    help: 'ヘルプ',
    askAnything: '何でも聞いてください',
    askLearning: '今日はどんなトピックを学びたいですか？',
    noHistory: '履歴がありません',
    noResult: '結果がありません',
    searchHistory: '履歴を検索...',
    logoutConfirmTitle: 'Zhiyouからサインアウトしますか？',
    logoutConfirmDesc: 'チャット履歴にアクセスするには、再度サインインする必要があります。',
    cancel: 'キャンセル',
    yesLogout: 'はい、サインアウトします',
    deleteChatTitle: 'チャット履歴を削除しますか？',
    deleteChatDesc: 'このチャットは完全に削除され、復元することはできません。',
    delete: '削除',
    login: 'ログイン',
    welcome: 'こんにちは',
    howCanIHelp: "私はZhiyou AIです。今日はどのようなご用件でしょうか？",
    addImage: '画像',
    addVideo: '動画',
    addDoc: 'ドキュメント',
    addFile: 'ファイルを追加',
    fileTooLarge: 'ファイルサイズが大きすぎます。最大20MBです。',
    fileTypeNotSupported: 'サポートされていないファイル形式です。',
    fileReadError: 'ファイルの読み込みに失敗しました。',
    uploading: 'アップロード中...',
    done: '完了',
    magicTool: '魔法のツールを使う',
    searchWeb: 'ウェブ検索',
    sources: 'ソース',
    others: '他',
    copySuccess: 'テキストをコピーしました！',
    shareSuccess: '共有しました！',
    feedbackTitle: 'フィードバックを送信',
    feedbackPlaceholder: '何が問題だったか教えてください...',
    submit: '送信',
    disclaimer: 'Zhiyou AIは間違いを犯す可能性があります。重要な情報は再確認してください。',
    language: '言語',
    selectLanguage: '言語を選択',
    backToHome: 'ホームに戻る',
    save: '保存',
    thinking: '考えています',
    searching: '検索しています',
    modelZhiyou25: 'Zhiyou 2.5',
    modelZhiyou25Desc: '高速・効率的',
    modelZhiyou3: 'Zhiyou 3',
    modelZhiyou3Desc: '推論・数学',
    aspectRatio: 'アスペクト比',
    systemPromptBase: "あなたはZhiyou AIです。Zent Technology GHの賢くフレンドリーなAIアシスタントです。明示的に尋ねられない限り、創設者や開発者の名前を頻繁に言及しないでください。Zhiyou AIとしてのアイデンティティに集中してください。",
    systemPromptLang: "常に日本語で返答してください。",
    systemPromptReasoning: "あなたは現在Zhiyou 3として動作しています。回答の最初に「Zhiyou AIとして、私は分析します...」というフレーズを一度だけ使用してください。非常に深く、段階的に（ステップバイステップで）考え、答えを出す前にすべての視点を分析する必要があります。思考/推論プロセス全体を必ず <think> タグと </think> タグの中に配置してください。</think> タグの後に、非常に包括的で、論理的で、構造化された最終的な回答を提供してください。結論を急がないでください。",
    reasoningProcess: "推論プロセス",
    systemPromptResearch: "あなたは現在、シニアリサーチャー（Senior Researcher）として活動しています。回答の最初に「Zhiyou AIとして、私は...に関するデータを調査します」というフレーズを一度だけ使用してください。あなたの任務は、与えられたトピックについて詳細な調査を行うことです。Google検索ツールを使用して、さまざまなソースから最新かつ正確な情報を見つけてください。背景、詳細な分析、裏付けデータ、および強力な結論を網羅した、非常に包括的な調査レポートを提供してください。必要に応じて、表、リスト、引用を含む高度に構造化されたMarkdown形式を使用してください。",
    systemPromptLearning: "あなたは現在、ガイド付き学習モードの個人チューター（Personal Tutor）として活動しています。回答の最初に「Zhiyou AIとして、一緒にこれを学びましょう...」というフレーズを一度だけ使用してください。あなたの任務は、質問されたトピックについて段階的な（ステップバイステップの）説明を提供することです。Google検索ツールを使用して、関連性のある正確なソースを含めてください。複雑な概念を理解しやすい部分に分解し、必要に応じて類推を使用し、具体的な例を提供してください。説明の最後には必ずソースリンクを含めてください。",
    featureGenerateImage: '画像を生成',
    imageGenSuccess: 'Zhiyou AIとして、ご要望に基づいて画像を作成しました：',
    imageSearchSuccess: 'Zhiyou AIとして、関連する画像をいくつか見つけました：',
    featureDeepResearch: '深い研究 (Deep Research)',
    featureGuidedLearning: 'ガイド付き学習',
    featureSearchImage: '画像検索',
    describeSearchImage: '検索したい画像を説明してください',
    featureComingSoon: 'この機能は近日公開予定です！',
    signIn: 'サインイン',
    newUser: '新規ユーザーですか？',
    createAccount: 'アカウントを作成',
    emailAddress: 'メールアドレス',
    password: 'パスワード',
    forgotPassword: 'パスワードをお忘れですか？',
    continueWithGoogle: 'Googleで続行',
    loginError: 'Googleでのログインに失敗しました。もう一度お試しください。',
    emailLoginNotImplemented: 'メールログインはまだ実装されていません。',
    termsAndPrivacy: 'アカウントでサインインすることにより、SOの利用規約とプライバシーポリシーに同意したことになります。',
  },
  ko: {
    newChat: '새 채팅',
    chatHistory: '채팅 기록',
    settings: '설정',
    help: '도움말',
    askAnything: '무엇이든 물어보세요',
    askLearning: '오늘은 어떤 주제를 배우고 싶으신가요?',
    noHistory: '기록이 없습니다',
    noResult: '결과가 없습니다',
    searchHistory: '기록 검색...',
    logoutConfirmTitle: 'Zhiyou에서 로그아웃하시겠습니까?',
    logoutConfirmDesc: '채팅 기록에 액세스하려면 다시 로그인해야 합니다.',
    cancel: '취소',
    yesLogout: '예, 로그아웃합니다',
    deleteChatTitle: '채팅 기록을 삭제하시겠습니까?',
    deleteChatDesc: '이 채팅은 영구적으로 삭제되며 복구할 수 없습니다.',
    delete: '삭제',
    login: '로그인',
    welcome: '안녕하세요',
    howCanIHelp: "저는 Zhiyou AI입니다. 오늘 무엇을 도와드릴까요?",
    addImage: '이미지',
    addVideo: '비디오',
    addDoc: '문서',
    addFile: '파일 추가',
    fileTooLarge: '파일 크기가 너무 큽니다. 최대 20MB입니다.',
    fileTypeNotSupported: '지원되지 않는 파일 형식입니다.',
    fileReadError: '파일을 읽지 못했습니다.',
    uploading: '업로드 중...',
    done: '완료',
    magicTool: '마법 도구 사용',
    searchWeb: '웹 검색',
    sources: '출처',
    others: '기타',
    copySuccess: '텍스트가 복사되었습니다!',
    shareSuccess: '성공적으로 공유되었습니다!',
    feedbackTitle: '피드백 보내기',
    feedbackPlaceholder: '무엇이 잘못되었는지 알려주세요...',
    submit: '제출',
    disclaimer: 'Zhiyou AI는 실수를 할 수 있습니다. 중요한 정보는 다시 확인해주세요.',
    language: '언어',
    selectLanguage: '언어 선택',
    backToHome: '홈으로 돌아가기',
    save: '저장',
    thinking: '생각 중',
    searching: '검색 중',
    modelZhiyou25: 'Zhiyou 2.5',
    modelZhiyou25Desc: '빠르고 효율적',
    modelZhiyou3: 'Zhiyou 3',
    modelZhiyou3Desc: '추론 및 수학',
    aspectRatio: '종횡비',
    systemPromptBase: "당신은 Zhiyou AI입니다. Zent Technology GH의 똑똑하고 친절한 AI 비서입니다. 명시적으로 질문을 받지 않는 한 설립자나 개발자의 이름을 너무 자주 언급하지 마십시오. Zhiyou AI로서의 정체성에 집중하십시오.",
    systemPromptLang: "항상 한국어로 대답해 주세요.",
    systemPromptReasoning: "당신은 현재 Zhiyou 3로 작동하고 있습니다. 답변 시작 부분에 'Zhiyou AI로서 분석을 시작하겠습니다...'라는 문구를 한 번만 사용하십시오. 대답을 제공하기 전에 매우 깊이, 단계별로(step-by-step) 생각하고 모든 관점을 분석해야 합니다. 전체 생각/추론 과정을 반드시 <think> 및 </think> 태그 안에 넣어야 합니다. </think> 태그 뒤에 매우 포괄적이고 논리적이며 구조화된 최종 답변을 제공하십시오. 결론을 서두르지 마십시오.",
    reasoningProcess: "추론 과정",
    systemPromptResearch: "당신은 이제 수석 연구원(Senior Researcher)으로 활동하고 있습니다. 답변 시작 부분에 'Zhiyou AI로서 ...에 대한 데이터를 조사하겠습니다'라는 문구를 한 번만 사용하십시오. 당신의 임무는 주어진 주제에 대해 심층적인 연구를 수행하는 것입니다. Google 검색 도구를 사용하여 다양한 소스에서 최신의 정확한 정보를 찾으십시오. 배경, 심층 분석, 지원 데이터 및 강력한 결론을 다루는 매우 포괄적인 연구 보고서를 제공하십시오. 필요한 경우 표, 목록 및 인용이 포함된 고도로 구조화된 Markdown 형식을 사용하십시오.",
    systemPromptLearning: "당신은 이제 가이드 학습 모드에서 개인 튜터(Personal Tutor)로 활동하고 있습니다. 답변 시작 부분에 'Zhiyou AI로서 함께 배워봅시다...'라는 문구를 한 번만 사용하십시오. 당신의 임무는 요청된 주제에 대해 단계별(step-by-step) 설명을 제공하는 것입니다. Google 검색 도구를 사용하여 관련성 있고 정확한 출처를 포함하십시오. 복잡한 개념을 이해하기 쉬운 부분으로 나누고, 필요한 경우 유추를 사용하며, 구체적인 예를 제공하십시오. 설명 끝에는 항상 출처 링크를 포함하십시오.",
    featureGenerateImage: '이미지 생성',
    imageGenSuccess: 'Zhiyou AI로서 요청하신 내용을 바탕으로 이미지를 생성했습니다:',
    imageSearchSuccess: 'Zhiyou AI로서 귀하를 위한 몇 가지 관련 이미지를 찾았습니다:',
    featureDeepResearch: '심층 연구 (Deep Research)',
    featureGuidedLearning: '가이드 학습',
    featureSearchImage: '이미지 검색',
    describeSearchImage: '찾고 싶은 이미지를 설명해 주세요',
    featureComingSoon: '이 기능은 곧 제공될 예정입니다!',
    signIn: '로그인',
    newUser: '새 사용자이신가요?',
    createAccount: '계정 만들기',
    emailAddress: '이메일 주소',
    password: '비밀번호',
    forgotPassword: '비밀번호를 잊으셨나요?',
    continueWithGoogle: 'Google로 계속하기',
    loginError: 'Google 로그인에 실패했습니다. 다시 시도해 주세요.',
    emailLoginNotImplemented: '이메일 로그인은 아직 구현되지 않았습니다.',
    termsAndPrivacy: '계정으로 로그인하면 SO의 서비스 약관 및 개인정보 보호정책에 동의하는 것입니다.',
  },
  zh: {
    newChat: '新对话',
    chatHistory: '聊天记录',
    settings: '设置',
    help: '帮助',
    askAnything: '问任何问题',
    askLearning: '您今天想学习什么主题？',
    noHistory: '暂无记录',
    noResult: '没有结果',
    searchHistory: '搜索记录...',
    logoutConfirmTitle: '退出 Zhiyou？',
    logoutConfirmDesc: '您需要重新登录才能访问您的聊天记录。',
    cancel: '取消',
    yesLogout: '是的，退出',
    deleteChatTitle: '删除聊天记录？',
    deleteChatDesc: '此聊天将被永久删除，无法恢复。',
    delete: '删除',
    login: '登录',
    welcome: '你好',
    howCanIHelp: "我是 Zhiyou AI。今天我能帮您什么？",
    addImage: '图片',
    addVideo: '视频',
    addDoc: '文档',
    addFile: '添加文件',
    fileTooLarge: '文件太大。最大为 20MB。',
    fileTypeNotSupported: '不支持的文件类型。',
    fileReadError: '读取文件失败。',
    uploading: '上传中...',
    done: '完成',
    magicTool: '使用魔法工具',
    searchWeb: '搜索网络',
    sources: '来源',
    others: '其他',
    copySuccess: '文本已复制！',
    shareSuccess: '分享成功！',
    feedbackTitle: '发送反馈',
    feedbackPlaceholder: '告诉我们出了什么问题...',
    submit: '提交',
    disclaimer: 'Zhiyou AI 可能会犯错。请核实重要信息。',
    language: '语言',
    selectLanguage: '选择语言',
    backToHome: '返回主页',
    save: '保存',
    thinking: '思考中',
    searching: '搜索中',
    modelZhiyou25: 'Zhiyou 2.5',
    modelZhiyou25Desc: '快速高效',
    modelZhiyou3: 'Zhiyou 3',
    modelZhiyou3Desc: '推理与数学',
    aspectRatio: '宽高比',
    systemPromptBase: "你是 Zhiyou AI，来自 Zent Technology GH 的聪明友好的 AI 助手。除非被明确问及，否则不要过于频繁地提及创始人或开发者的名字。专注于你作为 Zhiyou AI 的身份。",
    systemPromptLang: "请始终用中文（简体）回复。",
    systemPromptReasoning: "你现在作为 Zhiyou 3 运行。请在回答开头使用一次“作为 Zhiyou AI，我将进行分析……”的短语。你必须非常深入地、一步一步地思考，在给出答案之前分析每一个视角。你必须将整个思考/推理过程放在 <think> 和 </think> 标签内。在 </think> 标签之后，提供非常全面、合乎逻辑且结构化的最终答案。不要急于下结论。",
    reasoningProcess: "推理过程",
    systemPromptResearch: "你现在担任高级研究员 (Senior Researcher)。请在回答开头使用一次“作为 Zhiyou AI，我将研究关于……的数据”的短语。你的任务是对给定主题进行深入研究。使用 Google 搜索工具从各种来源查找最新、准确的信息。提供一份非常全面的研究报告，涵盖背景、深入分析、支持数据和强有力的结论。必要时使用包含表格、列表和引用的高度结构化的 Markdown 格式。",
    systemPromptLearning: "你现在在引导学习模式下担任私人导师 (Personal Tutor)。请在回答开头使用一次“作为 Zhiyou AI，让我们一起学习这个……”的短语。你的任务是对所询问的主题提供循序渐进（step-by-step）的解释。使用 Google 搜索工具包含相关且准确的来源。将复杂的概念分解为易于理解的部分，必要时使用类比，并提供具体的例子。始终在解释结束时包含来源链接。",
    featureGenerateImage: '生成图片',
    imageGenSuccess: '作为 Zhiyou AI，我已经根据您的要求创建了图像：',
    imageSearchSuccess: '作为 Zhiyou AI，我已经为您找到了几张相关的图片：',
    featureDeepResearch: '深度研究 (Deep Research)',
    featureGuidedLearning: '引导学习',
    featureSearchImage: '搜索图片',
    describeSearchImage: '描述您想查找的图片',
    featureComingSoon: '此功能即将推出！',
    signIn: '登录',
    newUser: '新用户？',
    createAccount: '创建账号',
    emailAddress: '电子邮件地址',
    password: '密码',
    forgotPassword: '忘记密码？',
    continueWithGoogle: '使用 Google 继续',
    loginError: '使用 Google 登录失败。请重试。',
    emailLoginNotImplemented: '电子邮件登录尚未实现。',
    termsAndPrivacy: '登录账号即表示您同意 SO 的服务条款和隐私政策。',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window !== 'undefined') {
      const savedLang = localStorage.getItem('zhiyou_language') as Language;
      return (savedLang && translations[savedLang]) ? savedLang : 'id';
    }
    return 'id';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('zhiyou_language', lang);
  };

  const t = (key: string) => {
    return (translations[language] as any)[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
